---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod1 # 배포 이름
  labels:
    app: pod1 # 배포 이름
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod1 # 배포 이름
  template:
    metadata:
      labels:
        app: pod1 # 배포 이름
    spec:
      volumes:
      - name: data-volume # 볼륨명
        persistentVolumeClaim:
          claimName: mes-share-pvc
      containers:
      - name: pod1-service  # 컨테이너 이름
        image: "tomcat" # 이미지명 
        imagePullPolicy: Always
#        command: ["sleep"]
#        args: ["infinity"]
        ports: # 컨테이너 내부에서 사용하는 포트 명시
        - name: web
          containerPort: 8080
          protocol: TCP
        volumeMounts: # 영구 저장할 볼륨 (디렉토리) 설정
        - name: data-volume # 위에서 명시한 볼륨명 지정
          mountPath: /data # 서비스에서 필요한 경로 지정

---

apiVersion: v1
kind: Service
metadata:
  name: pod1-web # 서비스 이름
spec:
  selector:
    app: pod1 # 연결할 Deployment의 이름
  type: clusterIP
  ports:
  - name: web
    port: 8080
    protocol: TCP
