apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tmas-ing
  annotations:
    alb.ingress.kubernetes.io/network-type: 'private'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/description: 'tmas ingress controller'
    alb.ingress.kubernetes.io/healthcheck-port: '30181'
    alb.ingress.kubernetes.io/healthcheck-path: '/home'
  labels:
    app: tmas-ing
spec:
  ingressClassName: alb
  defaultBackend:
    service:
      name: tmas-sysmng-svc
      port: 
        number: 80
#  rules: 
#  - http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#           name: tmas-sysmng-svc
#            port:
#              number: 80
#       - path: /pod3
#         pathType: Prefix
#         backend:
#           service:
#             name: tmas-sysmng-svc
#             port:
#               number: 80
#              
#      - path: /pod4
#        pathType: Prefix
#        backend:
#          service:
#            name: pod4-web
#            port:
#              number: 80
