apiVersion: v1
kind: Service
metadata:
  name: base-svc-lb
  annotations:
    service.beta.kubernetes.io/ncloud-load-balancer-internal: "true"
spec:
        
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: base-web
  sessionAffinity: ClientIP
  type: LoadBalancer
