---
# tmas-sysmng service
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka-web # 배포 이름
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eureka-web # 배포 이름
  serviceName: eureka-service
  template:
    metadata:
      labels:
        app: eureka-web # 배포 이름
    spec:
      volumes:
      # - name: data-volume # 볼륨명
      #   persistentVolumeClaim:
      #     claimName: nas-shared-pvc
      containers:
      - name: eureka-web # 컨테이너 이름
        image: impix.kr.ncr.ntruss.com/eureka-service:latest # 이미지명 
        imagePullPolicy: Always # 항상 이미지 다운로드 받아서 실행
        ports: # 컨테이너 내부에서 사용하는 포트 명시
        - name: web
          containerPort: 80
          protocol: TCP
        # volumeMounts: # 영구 저장할 볼륨 (디렉토리) 설정
        # - name: data-volume # 위에서 명시한 볼륨명 지정
        #   mountPath: /data/mes_file # 서비스에서 필요한 경로 지정
      imagePullSecrets:            # 해당 images 를 받아올때 사용할 secret ojbect 설정
      - name: ncp-registry
      affinity: # 같은 노드에 배치되지 않도록 설정
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - eureka-web
            topologyKey: "kubernetes.io/hostname"   

---

apiVersion: v1
kind: Service
metadata:
  name: eureka-service # 서비스 이름
  labels:
    app: eureka-service
spec:
  sessionAffinity: ClientIP
  selector:
    app: eureka-web # 연결할 Deployment의 이름
  clusterIP: None
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP